# ===============================================
# CONFIGURA플O DO BANCO DE DADOS (PostgreSQL)
# ===============================================
spring.application.name=BackEnd

spring.datasource.url=jdbc:postgresql://localhost:5432/detalheprata_db
spring.datasource.username=postgres
spring.datasource.password=12345

# Atualiza automaticamente o schema do banco
spring.jpa.hibernate.ddl-auto=update

# Mostra SQL gerado no console
spring.jpa.show-sql=true

# Dialeto do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# CONFIGURA플O DO TOKEN JWT
# ===============================================
api.security.token.secret=meu-secret-super-secreto-e-longo-para-garantir-seguranca

# ===============================================
# CONFIGURA플O DE E-MAIL (GMAIL)
# ===============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contatodetalheprata@gmail.com
#TODO: REMOVER QUANDO ESTIVER EM DEPLOY   ***************************************************************
spring.mail.password=dyfotifipuscuswo
#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CONFIGURA플O DE UPLOAD
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================================
# CONFIGURA합ES EXTRAS
# ===============================================
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo
server.port=8080
server.error.include-stacktrace=always
debug=true

# ===============================================
# CONFIGURA플O TWILIO (WHATSAPP)
# ===============================================
#TODO: REMOVER QUANDO ESTIVER EM DEPLOY   ***************************************************************
twilio.account-sid=AC12297b573d4ea3920e4844937ff47414
twilio.auth-token=eeb2f657bb907d8e18b8b4a8e14e0418

#TODO: REMOVER QUANDO ESTIVER EM DEPLOY   ***************************************************************
twilio.phone-number=whatsapp:+14155238886

# ===============================================
# CONFIGURA플O DO SITE (FRONT-END)
# ===============================================
website.url=http://localhost:3000

# ===============================================
# STRIPE (PROTEGIDO COM VARI햂EIS)
# ===============================================
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}